The flag 'directory' used in rule all is only valid for outputs, not inputs.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	2	bowtie2
	1	bowtie2_build
	2	fastp_se
	2	minimap2
	1	minimap2_index
	1	multiqc
	2	samtools_decontaminated
	1	woltka_classify
	1	woltka_gotu
	14
Select jobs to execute...

[Thu Jan  7 13:13:38 2021]
rule fastp_se:
    input: ../../../raw_fastqs/ERR2242499.fastq.gz
    output: ../results/QC_reads/ERR2242499_fastp.fastq, ../results/QC_reads/report/ERR2242499_fastp.html, ../results/QC_reads/report/ERR2242499_fastp.json
    log: ../results/logs/fastp/se/ERR2242499.log
    jobid: 2
    benchmark: ../results/benchmarks/fastp_se/ERR2242499.tsv
    wildcards: sample=ERR2242499
    threads: 6

[Thu Jan  7 13:13:38 2021]
Error in rule fastp_se:
    jobid: 2
    output: ../results/QC_reads/ERR2242499_fastp.fastq, ../results/QC_reads/report/ERR2242499_fastp.html, ../results/QC_reads/report/ERR2242499_fastp.json
    log: ../results/logs/fastp/se/ERR2242499.log (check log file(s) for error message)

RuleException:
NameError in line 35 of /klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow/workflow/Snakefile:
name 'config' is not defined
  File "/home/kkopera/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2285, in run_wrapper
  File "/klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow/workflow/Snakefile", line 35, in __rule_fastp_se
  File "/home/kkopera/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/kkopera/.conda/envs/snakemake/lib/python3.6/concurrent/futures/thread.py", line 56, in run
  File "/home/kkopera/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/kkopera/.conda/envs/snakemake/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 2351, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow/workflow/.snakemake/log/2021-01-07T131338.476922.snakemake.log
